### ISSUE TITLE
Provide a means to configure connection to existing Blockchain Network

### ISSUE THREAD

**Issue by bobbiejc** [sstone1/blockchain-starter-kit#13]

**Comment by anouq** [comment]
Hi,

I recommend checking out the following tutorial: https://www.ibm.com/developerworks/cloud/library/cl-deploy-blockchain-starter-plan-network/. Step 1-9 walks you through creating and deploying a business network archive, which you can use in step 8 of Simon's tutorial.

**Comment by jt-nti** [comment]
Hi @bobbiejc, I think this should have been covered by #8 - that allows an existing blockchain service and/or an existing cloudant service to be specified - or were you looking for something different?

**Comment by bobbiejc** [comment]
Yes!  covered. Thanks!
