### ISSUE TITLE
Work out how to manage updates to scripts

### ISSUE THREAD

**Issue by caroline-church** [sstone1/blockchain-starter-kit#17]

**Comment by jt-nti** [comment]
A possible approach is to copy over scripts from a library repository (could be the same repository that holds the toolchain template, or a separate repository). I've prototyped this with a "prepare" job in https://github.com/hyperledger-composer-samples/hyperledger-composer-toolchain

**Comment by jt-nti** [comment]
Now covered in IBM-Blockchain-Starter-Kit/build-lib#5
