### ISSUE TITLE
Question - on positioning.

### ISSUE THREAD

**Issue by mbwhite** [sstone1/blockchain-starter-kit#2]
**As-is:** 

This is a sample toolchain, that will provide a blockchain starter plan, deploy 0-n Smart Contracts (Fabric ChainCode or Composer Framework)

Has theoretical space where by other parts of the stack could be deployed.

**to-be**
Should be able to deploy locally as well as in the cloud
The application part should be fixed in it's functionality - i.e. the tool chain calls NPM install in the directories and that's it... i.e. this should replace what ever technology is chosen by those developers.

### Assert that the AIM of this is to provide a **sample starter tool chain for Smart Contract deployment**, with **example only** of how the rest of a stack could follow suit.

^ as they say on exam papers.... discuss :-)

**Comment by sstone1** [comment]
As per the presentation I gave last week, the intention for the toolchain is to be able to deploy your smart contacts, backend applications, and front end applications. If we place some strict requirements around what the applications must look like - e.g. they must provide either a Cloud Foundry manifest file or a Docker file - then this should be trivial.
