### ISSUE TITLE
Deploy to IBM bluemix issue 

### ISSUE THREAD

**Issue by manish-khobragade** [sstone1/blockchain-starter-kit#33]
Hi, 
While using the blockchain toolkit to install my code on IBM bluemix Blockchain Services, deployment task gets failed with below error:

> ++ ls 'dist/*.bna'
ls: cannot access 'dist/*.bna': No such file or directory
+ BUSINESS_NETWORK_ARCHIVES=
++ exit_on_error
++ '[' 2 = 0 ']'
++ message='Unexpected Error'
++ echo 'ERROR: Unexpected Error'
ERROR: Unexpected Error
++ '[' '' '!=' '' -a https://blockchain-starter.ng.bluemix.net '!=' '' ']'
++ exit 1
FAILED
Error read/writing config:  getwd: no such file or directory

![toolchainissue](https://user-images.githubusercontent.com/40388104/44731091-1118fc80-ab00-11e8-8ea3-7653d6a4f27c.PNG)

What I was able to conclude from the log is that the below script is not getting executed

> "prepublish": "mkdirp ./dist && composer archive create --sourceType dir --sourceName . -a ./dist/XXXXXXXXXXXXX.bna"

Can you help me out in fixing this

**Comment by jt-nti** [comment]
Hi @manish-khobragade, I think that script should get run as part of the npm install in the test_composer_contract function in the pipeline-BUILD.sh script: https://github.com/sstone1/blockchain-starter-kit/blob/master/.bluemix/pipeline-BUILD.sh#L35

Do you see any errors in the log from the build stage?

**Comment by manish-khobragade** [comment]
Thanks @jt-nti  for the quick reply.
Although the build stage was seen as passed successully, I went on to check the logs after your suggestions above and did found it has reported error in my network's logic.js.
I wonder since there is error in  logic.js how come Build stage was showing as passed.
I was using lambda expression (=>) inside  Array.prototype.filter() function which I guess is not supported in the javascript version of IBM bluemix. Replacing lambda expression with anonymous function fixed this issue.

**Comment by jt-nti** [comment]
That's useful to know, thanks @manish-khobragade - I'll look out for that problem with the new starter kit project https://github.com/IBM-Blockchain-Starter-Kit
