### ISSUE TITLE
Can't deploy business networks anymore

### ISSUE THREAD

**Issue by eciggaar** [sstone1/blockchain-starter-kit#6]
It seems the new version of the gRPC library (https://github.com/hyperledger/composer/pull/3946)  is also causing issues to this blockchain starter kit. The network install step of the business network fails with exactly the same error as described in https://github.com/hyperledger/composer/issues/3944. I modified the function `install_composer` in the ./.bluemix/pipeline-COMMON.sh as follows (as suggested in the comments of https://github.com/hyperledger/composer/issues/3944:
```javascript
function install_composer {
    npm init -y
    npm install -g --save-dev grpc@1.10.1
    npm install -g --save composer-cli@0.18.1 @ampretia/composer-wallet-cloudant
}
```
However, no success. Would be great if this could be fixed for composer v0.18.1 
Let me know if you need more input.

**Comment by sstone1** [comment]
@eciggaar this should work now. Starter Plan has been upgraded to Fabric v1.1 GA as of yesterday afternoon, which means you can use Composer v0.19.x with Starter Plan. This Starter Kit has been updated to use Composer v0.19.x and has been confirmed working, so please try again!
